CREATE SCHEMA IF NOT EXISTS openinv;
USE openinv;
CREATE TABLE IF NOT EXISTS `items` (  `id` int(11) NOT NULL AUTO_INCREMENT,
`type` varchar(45) DEFAULT NULL,
`item` varchar(45) DEFAULT NULL,
`value` int(11) DEFAULT NULL,
PRIMARY KEY (`id`),
UNIQUE KEY `id_UNIQUE` (`id`)) ENGINE=InnoDB AUTO_INCREMENT=77 DEFAULT CHARSET=latin1
